// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_9qw35ZsYFRpJtsSFdh_FqnJN9N5QME',
    appId: '1:596028421555:web:a1f81d7015301155ee07c6',
    messagingSenderId: '596028421555',
    projectId: 'genrec-0298',
    authDomain: 'genrec-0298.firebaseapp.com',
    storageBucket: 'genrec-0298.firebasestorage.app',
    measurementId: 'G-J1K43QSLJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9eHY-zp5WOtEPX3x9Fek8zX4qNWCoK7U',
    appId: '1:596028421555:android:f8b11469fe095f34ee07c6',
    messagingSenderId: '596028421555',
    projectId: 'genrec-0298',
    storageBucket: 'genrec-0298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxAy3SBFJmvwkWGKL8zRjyDF6tGWV7CDA',
    appId: '1:596028421555:ios:9ce07797871da3fbee07c6',
    messagingSenderId: '596028421555',
    projectId: 'genrec-0298',
    storageBucket: 'genrec-0298.firebasestorage.app',
    iosBundleId: 'com.example.genrec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxAy3SBFJmvwkWGKL8zRjyDF6tGWV7CDA',
    appId: '1:596028421555:ios:9ce07797871da3fbee07c6',
    messagingSenderId: '596028421555',
    projectId: 'genrec-0298',
    storageBucket: 'genrec-0298.firebasestorage.app',
    iosBundleId: 'com.example.genrec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0_9qw35ZsYFRpJtsSFdh_FqnJN9N5QME',
    appId: '1:596028421555:web:2c5eaca1f6dd929dee07c6',
    messagingSenderId: '596028421555',
    projectId: 'genrec-0298',
    authDomain: 'genrec-0298.firebaseapp.com',
    storageBucket: 'genrec-0298.firebasestorage.app',
    measurementId: 'G-CKPGTLTSYF',
  );
}
